import sizes from './sizes';

export default {
  colorBox: {
    width: "20%",
    height: props => props.modeSingleColor ? "50%" : "25%",
    margin: "0 auto",
    display: "inline-block",
    position: "relative",
    cursor: "pointer",
    marginBottom: "-4px",
    backgroundColor: props => props.color[props.format],
    "&:hover button": {
      opacity: "1",
      transition: "all 0.3s ease",
    },
    [sizes.down("lg")]: {
      width: "25%",
      height: props => props.modeSingleColor ? "33.333%" : "20%",
    },
    [sizes.down("md")]: {
      width: "50%",
      height: props => props.modeSingleColor ? "20%" : "10%",
    },
    [sizes.down("xs")]: {
      width: "100%",
      height: props => props.modeSingleColor ? "10%" : "5%",
    } 
  },
  boxContent: {
    position: "absolute",
    padding: "10px",
    width: "100%",
    left: "0",
    bottom: "0",
    color: "black",
    letterSpacing: "1px",
    textTransform: "uppercase",
    fontSize: "12px",
  },
  seeMore: {
    color: props => props.color.luminance < 0.5 ? "white" : "black",
    background: "rgba(255, 255, 255, 0.3)",
    position: "absolute",
    border: "none",
    right: "0",
    bottom: "0",
    width: "60px",
    height: "30px",
    textAlign: "center",
    lineHeight: "30px",
    textTransform: "uppercase",
    outline: "none",
    cursor: "pointer",
  },
  copyOverlay: {
    opacity: "0",
    zIndex: "0",
    width: "100%",
    height: "100%",
    transition: "transform 0.6s ease-in-out",
    transform: "scale(0.1)",
    backgroundColor: props => props.color[props.format],
  },
  showOverlay: {
    opacity: "1",
    transform: "scale(50)",
    zIndex: "10",
    position: "absolute",
  },
  copyMessage: {
    position: "fixed",
    left: "0",
    right: "0",
    bottom: "0",
    top: "0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    fontSize: "4rem",
    transform: "scale(0.1)",
    opacity: "0",
    color: "white",
    "& h1": {
      fontWeight: "400",
      textShadow: "1px 2px black",
      background: "rgba(255, 255, 255, 0.3)",
      width: "100%",
      textAlign: "center",
      marginBottom: "0",
      padding: "1rem",
      textTransform: "uppercase",
      [sizes.down("xs")]: {
        fontSize: "5rem",
      }
    },
    "& p": {
      fontSize: "2rem",
      fontWeight: "100"
    }
  },
  showMessage: {
    opacity: "1",
    transform: "scale(1)",
    zIndex: "25",
    transition: "all 0.4s ease-in-out",
    transitionDelay: "0.3s",
  },
  copyButton: {
    cursor: "pointer",
    width: "100px",
    height: "30px",
    position: "absolute",
    display: "inline-block",
    top: "50%",
    left: "50%",
    outline: "none",
    background: "rgba(255, 255, 255, 0.3)",
    border: "none",
    opacity: "0",
    color: "white",
    lineHeight: "30px",
    fontSize: "1rem",
    textTransform: "uppercase",
    textAlign: "center",
    marginTop: "-15px",
    marginLeft: "-50px",
  },
  luminance: {
    color: props => props.color.luminance < 0.5 ? "white" : "black",
  },
};